name: "CI/CD_calendar-service-wip_master"

on:
  push:
    branches: [ tryworkflow ]
    paths:
      - "services/calendar-service-wip/**"
      - ".github/workflows/calendar-service-wip_master.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: calendar-service-wip

    
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@master

      - name: Install ğŸ”§
        run: npm ci
      
      - name: Lint ğŸ§
        run: npm run lint

      - name: Test ğŸš¨
        run: npm test
